name: Update VueTorrent

on:
  schedule:
  - cron: "0 2 * * *"
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:

  try-update-vuetorrent:
    runs-on: ubuntu-latest
    steps:
      - name: git-get-release-action
        id: git-get-release
        uses: cardinalby/git-get-release-action@1.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo: WDaan/VueTorrent
          latest: true

      - name: Checkout repository
        uses: actions/checkout@v3.5.3
        with:
          submodules: true

      - name: Get current commitish
        id: get-current-commitish
        run: |
          cd vue-torrent
          echo "Current commitish: $(git rev-parse HEAD)"
          echo "current_commitish=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare
        run: |
          echo "Lastest version: ${{ steps.git-get-release.outputs.tag_name }}"
          echo "Lastest commitish: ${{ steps.git-get-release.outputs.target_commitish }}"
          echo "Need update: ${{ steps.git-get-release.outputs.target_commitish != steps.get-current-commitish.outputs.current_commitish }}"
          echo "should_update=${{ steps.git-get-release.outputs.target_commitish != steps.get-current-commitish.outputs.current_commitish }}" >> $GITHUB_OUTPUT

      - name: Update
        if: steps.compare.outputs.should_update == 'true'
        working-directory: ./vue-torrent
        run: |
          git fetch --depth=1 origin ${{ steps.git-get-release.outputs.tag_name }}
          git checkout -b ${{ steps.git-get-release.outputs.tag_name }} ${{ steps.git-get-release.outputs.target_commitish }}
          git reset --hard HEAD
          echo "Current commitish: $(git rev-parse HEAD)"

      - name: Commit changes
        if: steps.compare.outputs.should_update == 'true'
        run: |
          echo '${{ secrets.COMMIT_KEY }}' > /tmp/commit_key
          export GIT_SSH_COMMAND="ssh -i /tmp/commit_key -F /dev/null"

          git diff
          git config user.name "GitHub Actions"
          git config user.email "bot@noreply.github.com"
          git add .
          git commit -m "Update to ${{ steps.git-get-release.outputs.tag_name }}"
          git push origin ${{ github.ref_name }}

      - name: Tag
        if: steps.compare.outputs.should_update == 'true'
        run: |
          echo '${{ secrets.COMMIT_KEY }}' > /tmp/commit_key
          export GIT_SSH_COMMAND="ssh -i /tmp/commit_key -F /dev/null"

          git tag ${{ steps.git-get-release.outputs.tag_name }}
          git push origin ${{ steps.git-get-release.outputs.tag_name }}
